### PR TITLE
fixes #272 tokens assemble macros from files

### LINKED ISSUE #272: Build all macros into the token library
Rtfs

### PR DESCRIPTION
**Pull request by mr-ice**
This changes the assembly of tokens to pick up all .xml files that
are not otherwise known (content.xml, properties.xml, and
propertyMapCI.xml) and load them as macros.

The macroPropertiesMap from extract is still in the content.xml on
the filesystem, but it is no longer read (it is thrown away when loading
the asset from the filesystem).

### CODE REVIEW

**Comment by trey-kirk-sp** [comment]
On extract, are properties and macros zeroed out of context.xml? If not, can we start doing that since that data is now authoritative in other places?

**Comment by mr-ice** [comment]
> On extract, are properties and macros zeroed out of context.xml? 

macros are still stubbed out.  I think I will add that to this PR.

propertyMapCI is removed completely to its own file.

**Comment by mr-ice** [comment]
I should probably pull the <index> out of the macros as well, as that has to be set on assemble and should just be synthesized

**Comment by mr-ice** [comment]
now I'm running into the git tag that I'm not stripping on extract.

**Review by trey-kirk-sp — APPROVED** [review]

**Pull request merged**
